### ISSUE TITLE
Depth Map Image Not Updating Using Matplotlib

### ISSUE THREAD

**Issue by nrjbs87** [ifm/o3d3xx-python#1] opened 2016-10-26 18:32 UTC
I am trying to use Matplotlib to display the image of the depth map. I start by creating an ImageClient Object. I then call `.readNextFrame()` and store the 'distance' parameter from the result dictionary. I then convert the distance array to a numpy array so I can reshape it into the correct sized array. I then use Matplotlib's `im_show()` to display the distance array. 

```
import o3d3xx
import array
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

imageWidth = 176
imageHeight = 132

#create ImageClient Object
pcic = o3d3xx.ImageClient("169.254.251.183",50010)

#store distance array as variable 'distance'
result = pcic.readNextFrame()
distance = result["distance"]
#convert to np array and reshape 
distance = np.asarray(distance)
distance = distance.reshape(imageHeight,imageWidth)

#plot distance array
plt.figure()
plt.title("Distance Image")
plt.imshow(distance)
plt.show()
```

After using `imshow(distance)` the image shows up with no issues. The problem I am having is that once I dramatically move the camera so it is looking at a different scene and run `.readNextFrame()`, the image will not update and will still display the last scene. I know that the actual distance array is changing because I have compared the two arrays from one scene to the next. The only way I can get around this issue is by creating a new ImageClient object but I would like to avoid that. 

Any ideas as to how to get around this? Ultimately I would like `imshow()` to display a new image once the scene has changed without creating a new ImageClient object.

**Comment by cfreundl** [comment] 2016-10-27 08:06
On first glance this seems to be an issue with matplotlib itself, as the contents of the array returned by the image client change with each call to `readNextFrame()`. I must admit that I am not an expert in the usage of matplotlib, I derived the `imager_viewer.py` script from another script a colleague gave to me.

But in order to get your issue sorted out, I suggest you try whether the example script works. As far as I can see, the main difference is that in the example the image is created only once using `imshow()` and afterwards only the changed data is replaced by `set_array()` while your script creates a new image for every frame read from camera.

**Comment by nrjbs87** [comment] 2016-10-27 15:45
I originally thought it was an error with Matplotlib but after testing my code with an alternative 3D sensor and following the same method, the images updated normally. Therefore, I figured the issue was due to a characteristic of the camera. 

`image_viewer.py` works normally for me. I noticed the `set_array()` method when looking through your code. Is this a method you wrote? I was unable to find any information about it online but was hoping to integrate it into my script.

**Comment by cfreundl** [comment] 2016-10-28 09:01
I guess that somewhere in your script a trigger for matplotlib to refresh the view is required. I tried to modify the `image_viewer.py` script wo resemble more your approach like this:

I replaced the animation call in `main()` with

```
ani = animation.FuncAnimation(fig, updatefig, interval=50, blit=True, fargs = [grabber,ax1,ax2])
```

i. e. I pass the axes objects instead of the image objects to the update function.

The update function has to be modified accordingly:

```
def updatefig(*args):
    g = args[1]
    g.readNextFrame();
    ax1 = args[2]
    amp_max = float(max(np.max(g.Amplitude),1));
    imAmp = ax1.imshow(g.Amplitude/ amp_max)
    ax1.set_title('Amplitude (Illu temp: %0.2f)'%(g.illuTemp))
    ax2 = args[3]
    dist_max = float(max(np.max(g.Distance),1));
    imDist = ax2.imshow(g.Distance/ dist_max)
    ax2.set_title('Distance')
    return imAmp, imDist
```

So, instead of calling `set_array()` `imshow()` is called during the update. This works fine, too, unless I leave out the `return imAmp, imDist` statement, then I see the same behavior as you describe: the first images are drawn and never updated afterwards. So I assume that the animation object automatically takes care to refresh all objects that are returned by the update function.

The `set_array()` method is part of matplotlib, however, I could not find it in the documentation of the `AxesImage` class myself, I guess it is part of the base class which is undocumented.

After googling the problem I found [this question on stackoverflow](http://stackoverflow.com/questions/4098131/how-to-update-a-plot-in-matplotlib). It looks like its answers could help you with the issue.

**Comment by nrjbs87** [comment] 2016-10-28 16:31
I have tested both of these methods with your `image_viewer.py` script and they both work flawlessly. Although I still have not fixed the issue on a frame to frame basis. 

I am running this code on a jupyter notebook currently and the cells are setup so that the function definitions of the class `GrabO3D300()`, the method `readNextFrame()` and the function `updatefigs()` are one cell. The second cell is then the `main()` function. I am experiencing the same problem when running the main script that the image is not updating. 

There are a few things I have noticed as well: 
1.  I was playing around with the `im.set_data()` and `im.set_array()` methods but was having some issues with it generating a nonetype. For example if I have an object `image = plt.imshow(data)`, I will create a matplotlib.image.AxesImage object. If i then go and write `new_image = image.set_data(new_data)`, new_image is returned as a nonetype variable and when i run `plt.show()` nothing will happens.
2. I noticed when positioning the camera from one scene to another, the camera would capture the transition in frame by frame images. If I would call `.readNextFrame()` multiple times between the first position of the camera and then the next, the images would show the transition. I’m not sure why this occurs as I would expect displaying the depth image on one scene, changing the position of the camera and then displaying the second depth image would consist of two discrete images, not everything in between. 

Thanks for the link as well as all of the help. I'll keep digging!

**Comment by cfreundl** [comment] 2016-10-31 08:33
Maybe I have found a solution that works for you, too. In order to reproduce your situation, I have removed the animation object in `examples/image_viewer.py` and replaced it with a `while` loop in which `updatefig()` is called repeatedly. First I have experienced the same behavior as you described, and after browsing some more documentation and stackoverflow, I found that the crucial step is to turn on matplotlib's interactive mode (the `plt.ion()` call). This is the changed `main()` function that worked for me:

```
def main():
    address = sys.argv[1]
    camData = o3d3xx.ImageClient(address, 50010)

    plt.ion()
    fig = plt.figure()
    grabber = GrabO3D300(camData)
    ax1 = fig.add_subplot(1, 2, 1)
    ax2 = fig.add_subplot(1, 2, 2)
    imAmplitude = ax1.imshow(np.random.rand(imageHeight,imageWidth))
    imDistance = ax2.imshow(np.random.rand(imageHeight,imageWidth))
    plt.show()

    while True:
        updatefig(fig, grabber, imAmplitude, imDistance)
        fig.canvas.draw()
        time.sleep(0.1)
```

**Comment by nrjbs87** [comment] 2016-11-02 14:34
I have a theory that the images may not be updating due to a buffer or a queue of sorts. Since the camera is constantly capturing images, each time I request an image capture, is it possible that it is displaying the next image that was sitting in the queue? This would explain why I had to request quite a few frames until the image would update from one scene to the next.

Is this a possibility? If so, is it possible to set the camera into a trigger mode opposed to a continuous capture?

**Comment by cfreundl** [comment] 2016-11-03 08:13
That is possible, the images are transferred via a TCP connection, so if you do not process the images fast enough on receiver side, the TCP buffers (on both sender and receiver side) will get filled before the first images are discarded.

You can put the camera in triggered mode by configuring the application accordingly. If you use the ifm Vision Assistant to to configure the application, you would have to set the "Trigger source" to "Process Interface" in the "Image settings" screen. If you create/configure the application "yourself" with the XMLRPC interface, you would have to set the application object's "TriggerMode" parameter to the value "2".

With an application configured like this you can send the trigger command over the PCIC connection. Currently, there are no high-level commands implemented on Python side but you can always send the PCIC commands as strings. The asynchronous trigger command "t" fits best for this purpose when you read back the result not directly as a response to the command but later on in the program. This modified main function illustrates how it should work:

```
def main():
    address = sys.argv[1]
    camData = o3d3xx.ImageClient(address, 50010)

    plt.ion()
    fig = plt.figure()
    grabber = GrabO3D300(camData)
    ax1 = fig.add_subplot(1, 2, 1)
    ax2 = fig.add_subplot(1, 2, 2)
    imAmplitude = ax1.imshow(np.random.rand(imageHeight,imageWidth))
    imDistance = ax2.imshow(np.random.rand(imageHeight,imageWidth))
    plt.show()

    while True:
        camData.sendCommand("t")
        updatefig(fig, grabber, imAmplitude, imDistance)
        fig.canvas.draw()
```

**Comment by nrjbs87** [comment] 2016-11-03 13:48
The `camData.sendCommand("t")` successfully returns an image as a bytearray. Does this need to be unpacked the same way `.readNextFrame()` unpacks data in order to build the 'results' dictionary?

**Comment by cfreundl** [comment] 2016-11-03 14:16
Actually, `camData.sendCommand("t")` should just return the PCIC answer which is either "*" if the trigger was executed successfully or "!" if there was an error. The images themselves are sent asynchronously, and in order for them to be received you have to call `readNextFrame()` after the trigger call as before.

**Comment by nrjbs87** [comment] 2016-11-03 18:03
I see, thanks for the feedback. So I am trying this method via the XMLRPC Interface right now:

```
import o3d3xx

#create ImageClient Object
pcic = o3d3xx.ImageClient("IP",50010)

#create Device Object
camera = o3d3xx.Device("IP")

#create Session Object
session = camera.requestSession()

#Create Edit Object
edit = session.startEdit()

#create application object for the application number I want to edit (#2)
#The trigger mode has been changed in the IFM software and I can verify that the trigger source is indeed process interface via application.getParameter("TriggerMode") and that the application is the one I want.

application = edit.editApplication(2) 
application.getParameter("TriggerMode")    
application.getParameter("Name")

pcic.sendCommand("t")
result = pcic.readNextFrame()
```

Currently `pcic.sendCommand("t")` is returning an `!` indicating that there is an error. Referencing the operation manual this means it can be:
1. Device is busy with an evaluation
2. Device is in an invalid state for this command, e.g. configuration mode
3. Device is set to a different trigger source
4. No active application

I have verified that the trigger source is for the process interface since `.getParamater("TriggerMode")` is returning "2". I tried to activate the application using the "a" command but was unable to get the syntax right. Do you think the "t" command is not sending because of a different error or because the application is not activated? What would the right syntax be to activate the application if its number was 2?

**Comment by nrjbs87** [comment] 2016-11-03 19:40
Scratch that, I found the issue. I was not closing out of the session before trying to trigger the camera. Once I sent the `session.cancelSession()` command, I could then successfully send the `pcic.sendCommand("t")` commands and `pcic.readNextFrame()` afterwards. As it stands this seems to have fixed the updating image issue!

```
import o3d3xx
import numpy as np
import matplotlib.pyplot as plt

imageWidth = 176
imageHeight = 132

pcic = o3d3xx.ImageClient("IP",50010)
camera = o3d3xx.Device("IP")

session = camera.requestSession()

edit = session.startEdit()

application = edit.editApplication(1) 
application.setParameter("TriggerMode", "2")
application.save()
session.cancelSession()

pcic.sendCommand("t")

result = pcic.readNextFrame()
distance = result["distance"]
distance = np.asarray(distance)
distance = distance.reshape(imageHeight,imageWidth)
print(distance)

plt.imshow(distance)
plt.show()
```

Now as long as the application I am in is set to trigger on the process interface, I can send the `"t"` command and read the frame after. After both of these calls my image will update!

**Comment by cfreundl** [comment] 2016-11-04 08:42
Nice to hear that now everything works as desired, so I will close this issue.

**Closed as completed by cfreundl** 2016-11-04 08:42 UTC

**Comment by nrjbs87** [comment] 2016-11-04 13:30
Great, thank you again for all of your help!
